### ISSUE TITLE
Add "hosting" and related categories

### ISSUE THREAD

**Issue by r3vit** [trungdq88/Awesome-Black-Friday-Cyber-Monday#100]
Hi,
in black friday and cyber monday I'll check out for offerts in hostings/domains category.

One example: [Aruba](https://hosting.aruba.it/black-friday-hosting-domini.aspx) gives from the italian website a 50% discount for the first year on every service (domains, hosting...)

Another example: [OVH](https://www.ovh.it/black-friday) gives discounts (up to 55%) for hosting and domains.

Last year (2021), for this type of services, I made a list of all the offerts: Redirect Pizza ([redirect.pizza](https://redirect.pizza/)) made 30% discount, Pcloud gives lifetime account for 75% discount, and many more (also not related to hosting but VPN, programming language courses....). Also on reddit r/sysadmin you can find some [others](https://www.reddit.com/r/sysadmin/comments/r1wlzq/black_friday_deals_2021/) :)

**Comment by trungdq88** [comment]
Feel free to send a PR! 😄
