### ISSUE TITLE
Deal was replaced back to the old one after Commit b1caa54

### ISSUE THREAD

**Issue by leotrieu** [trungdq88/Awesome-Black-Friday-Cyber-Monday#1179]
Hi guys,

I wanted to bring attention to an issue I've discovered in the repository. 
Following commit b1caa54, my deal has been inadvertently reverted to an outdated, invalid version. The deal was displaying correctly in the previous commit (3109701).

I'm referring to this one below (this is the correct version):
|  🤖 | [Bundle of AI Premium Series - 2024](https://code4startup.com/black_friday) | Learn all about AI and build real AI startup apps in 2 week. | 80% OFF with Lifetime Access + Full Source Code |

Could you please check? (this regression might affects other deals as well)

Thank you for maintaining this repository 🙏

**Comment by leotrieu** [comment]
I've just created a new pull request anyway.

**Comment by dqhieu** [comment]
Hi @leotrieu , sorry for the mistake, and thanks for creating the new PR. There was a conflict and looked like I messed up your deal. Is there anything else I can help?

**Comment by leotrieu** [comment]
No, all good. Thanks for your support, @dqhieu!
