### ISSUE TITLE
🤑 Thundercontent · Black Friday Deal 2022 → 50% OFF

### ISSUE THREAD

**Issue by GRSLfr** [trungdq88/Awesome-Black-Friday-Cyber-Monday#175]
For those who want to scale their content strategy with Thundercontent, I wanted to mark the occasion for Black Friday 2022!

So: ALL Thundercontent plans are 50% off.

You have this week, to enjoy: 50% off your Thundercontent Pro subscription.

To take advantage of this, click the "Upgrade Pro" button and enter the code 22BF50 in the payment form. This gift code is only valid until Monday, November 28, 2022 at midnight.

Now is the time for you to scale you content strategy thanks to AI.

Use Thundercontent and its AI to:

📃 Generate unique long-form SEO blog posts
🎯 Generate creative marketing copies
👄 Convert blog posts into natural-sounding AI voices

https://thundercontent.com/ ⚡️

**Comment by trungdq88** [comment]
please send a PR
