### ISSUE TITLE
Krock.io - Creative Collaboration and Video Review Software

### ISSUE THREAD

**Issue by guculmetal** [trungdq88/Awesome-Black-Friday-Cyber-Monday#239]
🌅**Name:** Krock.io
**Description:** Creative Collaboration and Video Review Software - One tool for animation and video production companies to collaborate on creative projects remotely. All teams and clients are in one space.
**Discount & Terms:** 50% OFF all annual subscriptions with code **KRBFRD220547**. Discount live until the 25th of November 2022
**Web-page:** https://krock.io

**Comment by trungdq88** [comment]
please open a PR instead
