### ISSUE TITLE
Discount code for course "Go In One Evening" not working

### ISSUE THREAD

**Issue by thecloudranger** [trungdq88/Awesome-Black-Friday-Cyber-Monday#715]
Course "Go In One Evening"  - 50% OFF with code BLACKFRIDAY does not work.

<img width="580" alt="CleanShot 2023-11-22 at 09 24 48@2x" src="https://github.com/trungdq88/Awesome-Black-Friday-Cyber-Monday/assets/30345929/bc340cb2-9ca3-4a71-8b9d-0eb2fd9ca6b2">

**Comment by gh-readonly-tdinh-me** [comment]
please contact them instead, I'll update the discount code once the push a fix PR
