### ISSUE TITLE
These types of promotions/discounts/deals will not be accepted:

### ISSUE THREAD

**Issue by trungdq88** [trungdq88/Awesome-Black-Friday-Cyber-Monday#74]
- 100% OFF deals will not be accepted.
- "Anti-sale"/"price increase soon" deals will not be accepted.
- "Free while in beta" deals will not be accepted.
- Pre-order deals will not be accepted.
- If you put your deal before the existing deals, it will not be accepted (because first come, first serve).
- Shortened links will not be not accepted.

**Comment by fardeenxyz** [comment]
|  🤑 | [Notion Website Kit](https://gum.co/notionwebsite) | collection of pre-populated templates that make it easy to setup a website using Notion. | 50% OFF - BF2022 |

**Comment by HollieLeadDev** [comment]
We have 20% off LeadDev Together group learning courses for engineering managers with the code BLACKFRIDAY https://events.leaddev.com/together

**Comment by FollowMarcos** [comment]
💰 Name: Avatar Maker AI
Description: Avatar/profile photo AI generator.
Discount & Terms: 30% OFF all packages with code **AVATARMAKERAI30**. Discount live until the 30th of November 2022,
https://avatarmakerai.art/

**Comment by lhexin** [comment]
Name: Solopreneur Runway Model
Description: A 20-min financial calculator that helps you work out how much money you need to fund your lifestyle and startup idea while you build. 
Discount:  50% off all products with code BF2022

https://byhazellim.gumroad.com/l/runway

**Comment by abhi725** [comment]
Name: UUKI

Description: UUKI Community platform helps you build meaningful relationships within your community through events, newsletters, and a community page with web3 integrations. 

Deal: UUKI Lifetime deal at 50% off of the recurring plan and Get Flat 30% off on all premium plans

Coupon code: BLACKFRIDAY30 

https://www.uuki.live/black-friday-cyber-monday

**Comment by abhi725** [comment]
Name: Vadootv

Description: 
Vadootv - Video hosting & marketing made simple by Vadoo

Online video hosting with a single click. Record, upload, embed, share, market videos on sites, email, social & more. Try it now, free on Vadoo

Deal: Vadoo Lifetime deal at 50% off of the recurring plan & get flat 30% off on all premium plans.

Coupon code: BLACKFRIDAY30

https://www.vadoo.tv/blackfriday-lifetime-deal-vadoo

**Comment by max-founderpass** [comment]
Name: FounderPass

Category: Startup SaaS/Tools or Misc
Description: Founder membership which gives over $300k of discounts for founders/startups on software and SaaS tools
Deal: 50% Off For Life

Coupon Code: Not Required

https://www.FounderPass.com/black-friday

**Comment by ArnaudBelinga** [comment]
Name: Breakcold

Category: SAAS/Sales Tool
Description: Generate leads & close deals in 2023, not in 2010 via Email, LinkedIn & Twitter
Deal: 40% Off For Life on the monthly plan

Coupon Code: Not Required

https://www.breakcold.com/

**Comment by Elion0512** [comment]
Name: SMBImg
Category: Design tools
Description: A web application that allows you to create customizable screenshots for Twitter, Instagram, App Store, Facebook and more. You can beautify a background, create a watermark, export output, save presets and automatically apply the last customizations. You can also convert images instantly and easily in all major image formats.
Deal: 50% off the annual plans
Coupon code: SMBIMG_BLACKFRIDAY
https://smbimg.com

**Comment by jokierjokier** [comment]
Name: Kon-Boot
Category: Utility Tools
Description: Utility for system admins / pentesters / cybersecurity people that allows you to login into target computer without knowing the password (it bypasses the password without introducing permanent changes to the system). Works on all Windows and macOS system. 
Deal: 25% OFF
Coupon Code: Requires special link: https://kon-boot.com/?NOVEMBER=1

**Comment by ajda00** [comment]
Name: Popsy

Category: Startup SaaS/Tools
Description: No-code website builder that works like Notion. Just start typing & create professional websites in seconds.
Deal: 30% off for 3 months on all websites

Coupon code: POPSY30

https://popsy.co/

**Comment by wijajo** [comment]
Name: Yepic Studio
Description: A text to video platform with industry-leading lip-sync. Simply paste in a text script, choose an AI avatar, choose from one of 480+ voices and 65+ languages, then click generate! A video will appear in minutes. Personal avatar creation available.
Deal: 50% on annual plans
Coupon code: BlackFriday22
www.yepic.ai/black-friday

**Comment by sanlinck** [comment]
Name: Shulex VOC
Description: For eCommerce Sellers. Useful Amazon Product Research Tool. AI driver gains product insights and customer insights from eCommerce Review&Feedback.

Deal: 99% on month plans, 10 free use code
Coupon code: BlackFriday22

[www.voc.ai](https://voc.ai/)

**Comment by daryacdr** [comment]
Name: Serverspace cloud provider
Description: Black Friday deal for new users for the first balance refill. For developers, startaps and SMbs
Deal: +50% cashaback bonuses to your account. 
Coupon code: HOTBFDEALSSS
https://serverspace.io/black-friday-cyber-monday/

**Comment by manojbabub** [comment]
Name: BoldDesk
Description: BoldDesk is a cloud-based, modern help desk ticketing system and knowledge base software for serving a wide range of customer support activities. 
Deal: Save up to 40% on an unlimited agents plan at $75.
Coupon Code: BLACKFRIDAY2022
https://www.bolddesk.com/black-friday

**Comment by amnesrine** [comment]
Name: StationDB
Category: Startup SaaS/Tools
Description: An instant no-code admin panel that allows you to quickly and easily edit your database without having to code! You can collaborate with others on your data, and integrate with external tools to automate everything. Plus, our white label feature lets you brand the platform however you like.
Deal: 70% off of the monthly subscriptions
Coupon code: STATIONDB70
https://www.stationdb.com/

**Comment by Aaikansh22** [comment]
Name: DronaHQ
Category: SaaS/Tools
Description: A low-code platform to build powerful internal apps, with an easy-to-use drag-and-drop interface. You can integrate your app with more than 50+ databases like MySQL, PostgreSQL, or MariaDB. It has 150+ pre-built UI components that save 100s of development hours.   
Deal: 30% off annually for 1st year or 25% off monthly for 2 months. Offer valid till Nov 30th
Get coupon code: https://www.dronahq.com/

**Comment by ikoichi** [comment]
Name: Hivoe

Category: Social Media Tools
Description: Kickstart new conversations and find leads via Twitter DMs
Deal: 30% Off for the 1st Year/Month

Coupon Code: BLACKFRIDAY22

https://www.hivoe.com
