### ISSUE TITLE
Will there be a 2024 edition?

### ISSUE THREAD

**Issue by erikjalevik** [trungdq88/Awesome-Black-Friday-Cyber-Monday#859]
As per title...

**Comment by manuelescrig** [comment]
Looking forward to it!

**Comment by Jaarson** [comment]
yes, looking forward to it as well

**Comment by dqhieu** [comment]
Let do it

**Comment by trungdq88** [comment]
It's here! https://github.com/trungdq88/Awesome-Black-Friday-Cyber-Monday/issues/860
